-- MySQL Script generated by MySQL Workbench
-- Fri May 31 11:47:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema A3_JA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema A3_JA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `A3_JA` DEFAULT CHARACTER SET utf8 ;
USE `A3_JA` ;

-- -----------------------------------------------------
-- Table `A3_JA`.`Atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Atracao` (
  `idAtracao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `capacidade_max` INT NOT NULL,
  PRIMARY KEY (`idAtracao`))
ENGINE = InnoDB;

INSERT INTO atracao (nome, capacidade_max) VALUES ("Piscina de bolinhas", 20);

-- -----------------------------------------------------
-- Table `A3_JA`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Pessoa` (
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A3_JA`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Responsavel` (
  `idResponsavel` INT NOT NULL AUTO_INCREMENT,
  `cpfPessoa` CHAR(11) NOT NULL,
  PRIMARY KEY (`idResponsavel`),
  INDEX `fk_Responsavel_Pessoa1_idx` (`cpfPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_Pessoa1`
    FOREIGN KEY (`cpfPessoa`)
    REFERENCES `A3_JA`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A3_JA`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Atendente` (
  `idAtendente` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `idAtracao` INT NOT NULL default 1,
  `cpfPessoa` CHAR(11) NOT NULL,
  PRIMARY KEY (`idAtendente`),
  INDEX `fk_Atendente_Atracao1_idx` (`idAtracao` ASC) VISIBLE,
  INDEX `fk_Atendente_Pessoa1_idx` (`cpfPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Atendente_Atracao1`
    FOREIGN KEY (`idAtracao`)
    REFERENCES `A3_JA`.`Atracao` (`idAtracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendente_Pessoa1`
    FOREIGN KEY (`cpfPessoa`)
    REFERENCES `A3_JA`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A3_JA`.`Filho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Filho` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `data_nasc` DATE NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A3_JA`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `principal` CHAR(11) NOT NULL,
  `secundario` CHAR(11) NULL,
  `cpfPessoa` CHAR(11) NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Pessoa1_idx` (`cpfPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa1`
    FOREIGN KEY (`cpfPessoa`)
    REFERENCES `A3_JA`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `A3_JA`.`Filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `A3_JA`.`Filiacao` (
  `id_Filiacao` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `cpfResponsavel` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_Filiacao`),
    FOREIGN KEY (`matricula`)
    REFERENCES `A3_JA`.`Filho` (`matricula`),
    FOREIGN KEY (`cpfResponsavel`)
    REFERENCES `A3_JA`.`Responsavel` (`cpfPessoa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_SAFE_UPDATES = 0;

-- drop database a3_ja;



-- delete from telefone where telefone.cpfPessoa = "12345678904";

-- select * from Pessoa inner join telefone where pessoa.cpf = telefone.cpfPessoa;
-- insert into filho(nome, data_nasc) values ("Roberto Carlos", '1979-12-25'), ("Roberto Dinamite", '1999-04-07');
-- select * from filho;
-- select atracao.nome, pessoa.nome, atendente.usuario, atendente.senha, telefone.principal from atendente inner join atracao inner join pessoa inner join telefone where atendente.cpfPessoa = pessoa.cpf and atendente.cpfPessoa = pessoa.cpf and atendente.idAtracao = atracao.idAtracao;

-- UPDATE pessoa inner join atendente SET usuario = "teste", senha = "teste" WHERE pessoa.cpf =  atendente.cpfPessoa AND atendente.cpfPessoa = "12345678905";

-- select * from pessoa inner join atendente where pessoa.cpf = atendente.cpfPessoa;

-- select * from pessoa inner join responsavel where pessoa.cpf = responsavel.cpfPessoa;

-- insert into filiacao (matricula, cpfResponsavel) values (1, "12345678910"), (2, "12345678909");

 SELECT filho.nome as nomeFilho, pessoa.nome as nomePai FROM filho
 INNER JOIN filiacao
 INNER JOIN responsavel
 INNER JOIN pessoa
 WHERE filho.matricula = filiacao.matricula
 AND filiacao.cpfResponsavel = responsavel.cpfPessoa
 AND responsavel.cpfPessoa = pessoa.cpf;

-- select * from filho;

-- select max(idResponsavel) as lastResp inner join pessoa from responsavel;
-- select max(matricula) as lastFilho from filho;
-- select cpfPessoa from responsavel where idResponsavel = 3;
-- select * from responsavel;
-- SELECT * FROM Pessoa INNER JOIN telefone WHERE pessoa.cpf = telefone.cpfPessoa AND pessoa.nome = "Joao gabriel";
-- select * from atracao;
-- select * from telefone;
-- UPDATE atracao SET capacidade_max = 15 WHERE nome = "Piscina de bolinhas";
-- INSERT INTO telefone (principal, idPessoa) VALUES("21975996009", pessoa.cpf = "12345678901");
-- update telefone inner join pessoa set principal = "21975996008" where telefone.idPessoa = pessoa.idPessoa and pessoa.cpf = "12345678900";

-- insert into pessoa (nome, email, cpf, data_nasc) values ("joao gabriel", );

select * from atendente inner join pessoa inner join telefone  where atendente.cpfPessoa = pessoa.cpf and pessoa.cpf = telefone.cpfPessoa;

select * from responsavel inner join pessoa inner join telefone  where responsavel.cpfPessoa = pessoa.cpf and pessoa.cpf = telefone.cpfPessoa;

select * from pessoa inner join telefone where pessoa.cpf = telefone.cpfPessoa;

SELECT * FROM Pessoa INNER JOIN telefone WHERE pessoa.cpf = telefone.cpfPessoa AND pessoa.cpf = 75395185200;